BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),

]

BookStore/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('book/<int:book_id>', views.book, name='book'),
    path('user/<int:userx_id>', views.user, name='user'),
    path('authentication', views.authentication, name="authentication"),
    path('registration', views.registration, name="registration"),
    path('books_by_genre/<int:genre_id>', views.books_by_genre, name="books_by_genre"),
    path('books_by_country/<int:country_id>', views.books_by_country, name="books_by_country"),
    path('books_by_category/<int:category_id>', views.books_by_category, name="books_by_category"),
    path('exit_from_account', views.exit_from_account, name="exit_from_account"),
    path('search/', views.search, name="search"),
    path('rate_book/<int:book_id>', views.rate_book, name="rate_book"),

]

BookStore/mainapp/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    genre_name = models.CharField(max_length=100)
    def __str__(self):
        return self.genre_name


class User(models.Model):
    user_name = models.CharField(max_length=64)
    user_surname = models.CharField(max_length=64, default="UNKNOWN")
    user_login = models.CharField(max_length=64)
    user_password = models.CharField(max_length=64, default="qwe123ASD")
    user_url_image = models.CharField(max_length=1000, default='mainapp\images\defaultuser.png')
    user_role = models.CharField(max_length=32, default='user')
    user_status = models.CharField(max_length=16, default='not banned')

    def __str__(self):
        return self.user_name


class Country(models.Model):
    country_name = models.CharField(max_length=100)

    def __str__(self):
        return self.country_name


class Category(models.Model):
    PARAMETERS = (
        ('book_main_rating', 'book_main_rating'),
        ('book_critics_raing', 'book_critics_raing'),
        ('book_user_rating', 'book_user_rating'),
        ('book_year', 'book_year')
    )
    category_name = models.CharField(max_length=100)
    category_order_by_parameter = models.CharField(max_length=32, choices=PARAMETERS, default='book_main_rating')

    def __str__(self):
        return self.category_name


class Volume(models.Model):
    volume = models.CharField(max_length=100)
    chapter = models.CharField(max_length=100)

    def __str__(self):
        return self.chapter


class Book(models.Model):
    book_name = models.CharField(max_length=100)
    book_author = models.CharField(max_length=100)
    book_desctiption = models.TextField()
    book_url_image = models.CharField(max_length=1000)
    book_year = models.DateField()
    book_price =  models.CharField(max_length=100)
    book_publisher = models.CharField(max_length=100)
    book_categories = models.OneToOneField(Category, on_delete=models.CASCADE)
    book_country = models.OneToOneField(Country, on_delete=models.CASCADE)
    book_image = models.ImageField(blank=True, null=True, default=None, upload_to="images/books")
    book_user_rating = models.FloatField(default=0.0)
    book_main_rating = models.FloatField(default=0.0)
    book_critics_raing = models.FloatField(default=0.0)

    def __str__(self):
        return self.book_name


class Manga_comics(models.Model):
    manga_comics_name = models.CharField(max_length=100)
    manga_comics_desctiption = models.TextField()
    manga_url_image = models.CharField(max_length=1000)
    manga_comics_year = models.DateField()
    manga_comics_categories = models.OneToOneField(Category, on_delete=models.CASCADE)
    manga_comics_volume =  models.OneToOneField(Volume, on_delete=models.CASCADE)
    manga_comics_price = models.CharField(max_length=100)

    def __str__(self):
        return self.manga_comics_name


class Magazine(models.Model):
    magazine_name =  models.CharField(max_length=100)
    magazine_year = models.DateField()
    magazine_url_image = models.CharField(max_length=1000)
    magazine_categories = models.OneToOneField(Category, on_delete=models.CASCADE)
    magazine_country = models.OneToOneField(Country, on_delete=models.CASCADE)
    magazine_chapter = models.CharField(max_length=100)
    magazine_price =  models.CharField(max_length=100)

    def __str__(self):
        return self.magazine_name


class Favorite_book(models.Model):
    favorite_user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    favorite_book = models.ForeignKey(Book, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.favorite_book


class Favorite_manga(models.Model):
    favorite_user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    favorite_manga = models.ForeignKey(Manga_comics, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.favorite_manga


class Favorite_magazine(models.Model):
    favorite_user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    favorite_magazine = models.ForeignKey(Magazine, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.favorite_magazine



class Rating(models.Model):
    rating_user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating_book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating_number = models.IntegerField()

BookStore/mainapp/forms.py
from django import forms
from .models import *


class UploadImageForm(forms.Form):
    image = forms.ImageField()


class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'book_name',
            'book_desctiption',
            'book_country',
            'book_price',
            'book_year',
            'book_author',
            'book_publisher',
            'book_categories',
            'book_image',
        ]

BookStore/mainapp/views.py
import books as books
from django.shortcuts import render, get_object_or_404
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import datetime
from random import randint
from .forms import *

def index(request):
    context = dict(create_default_context())
    try:
        error = request.session['error']
        context['error'] = error
        del request.session['error']
    except:
        pass

    try:
        user = User.objects.get(pk=request.session['user_id'])
        context['user'] = user
    except:
        pass
    stars = []
    for book in context['books']:
        stars.append(get_rating_in_stars_list(book.book_user_rating / 2)[0:5])
    item_list = zip(context['books'], stars)
    context['item_list'] = item_list
    return render(request, "mainapp/index.html", context)


def rate_book(request, book_id):
    bookx = get_object_or_404(Book, pk=book_id)
    try:
        ratings = Rating.objects.filter(rating_movie=bookx)
        userx = User.objects.get(pk=request.session['user_id'])
        for i in ratings:
            if i.rating_user == userx:
                return HttpResponseRedirect(reverse('mainapp:book', args=(book_id,)))
        rating_number = int(request.POST['new_rating'])
        new_rating = Rating(rating_user=userx, rating_movie=bookx, rating_number=rating_number)
        new_rating.save()
        sum_of_rating =bookx.movie_user_rating * len(ratings) + rating_number
        bookx.movie_user_rating = sum_of_rating / (len(ratings) + 1)
        bookx.save()
    except:
        pass
    return HttpResponseRedirect(reverse('mainapp:book', args=(book_id,)))


def books_by_genre(request, genre_id):
    context = dict(create_default_context())
    user = None
    try:
        user = User.objects.get(pk=request.session['user_id'])
    except:
        pass
    genre = Genre.objects.get(pk=genre_id)
    found_movies = Book.objects.filter(book_genres=genre)
    context['found_books'] = found_movies
    context['user'] = user
    return render(request, "mainapp/search.html", context)


def books_by_country(request, country_id):
    context = dict(create_default_context())
    user = None
    try:
        user = User.objects.get(pk=request.session['user_id'])
    except:
        pass
    country = Country.objects.get(pk=country_id)
    found_books =Book.objects.filter(book_country=country)
    context['found_books'] = found_books
    context['user'] = user
    return render(request, "mainapp/search.html", context)


def books_by_category(request, category_id):
    context = dict(create_default_context())
    user = None
    try:
        user = User.objects.get(pk=request.session['user_id'])
    except:
        pass
    category = Category.objects.get(pk=category_id)
    found_books = Book.objects.filter(book_categories=category)
    context['found_books'] = found_books
    context['user'] = user
    return render(request, "mainapp/search.html", context)


def user(request, userx_id):
    genres = Genre.objects.all()
    countries = Country.objects.all()

    userx = get_object_or_404(User, pk=userx_id)

    context = {'userx': userx, 'user': None, 'genres': genres, 'countries': countries,
               'favorites': None}

    user = None

    try:
        favorites = Favorite_book.objects.filter(favorite_user=userx)
        context['favorites'] = favorites
    except:
        pass
    return render(request, "mainapp/user.html", context)


def authentication(request):
    books = Book.objects.order_by('book_main_rating')
    genres = Genre.objects.all()
    countries = Country.objects.all()
    new_books = Book.objects.order_by('book_year')[:2]
    context = {'books': books,
               'countries': countries,
               'new_books': new_books,
               'user': None,
               'error': None}
    try:
        user_login = request.POST['user_login']
        user_password = request.POST['user_password']
        try:
            user = User.objects.get(user_login=user_login)
        except:
            request.session['error'] = "Неправильное имя пользователя"
            return HttpResponseRedirect(reverse('mainapp:index'))

        if user_password != user.user_password:
            request.session['error'] = "Неверный пароль"
            return HttpResponseRedirect(reverse('mainapp:index'))

        if user and user_password == user.user_password:
            request.session['user_id'] = user.id
            context['user'] = user
    except:
        pass
    return HttpResponseRedirect(reverse('mainapp:index'))


def registration(request):
    books = Book.objects.order_by('book_main_rating')
    genres = Genre.objects.all()
    countries = Country.objects.all()
    new_books = Book.objects.order_by('book_year')[:2]
    context = {'books': books,
               'countries': countries,
               'new_books': new_books,
               'user': None,
               'error': None}
    try:
        user = User.objects.get(pk=request.session['user_id'])
        context['user'] = user
        return render(request, "mainapp/index.html", context)
    except:
        pass
    try:
        user_name = request.POST['name']
        user_surname = request.POST['surname']
        user_login = request.POST['login']
        user_password = request.POST['password']
        user_conform_password = request.POST['conform-password']

        if user_password != user_conform_password:
            request.session['error'] = "Пароль и подтверждение пароля не совпадают"
            return HttpResponseRedirect(reverse('mainapp:index'))

        try:
            userx = User.objects.get(user_login=user_login)
            request.session['error'] = "Имя пользователя уже занято"
            return HttpResponseRedirect(reverse('mainapp:index'))
        except:
            pass

        user = User(user_name=user_name, user_surname=user_surname, user_login=user_login, user_password=user_password)
        user.save()
        request.session['user_id'] = user.id
        context['user'] = user
    except:
        pass
    return HttpResponseRedirect(reverse('mainapp:index'))

def get_rating_in_stars_list(rating):
    counter = int(rating)
    stars = [2 for i in range(counter)]
    if counter < rating:
        stars.append(1 if rating >= float(counter) + 0.5 else 0)
    if counter < rating:
        counter += 1
    for i in range(10 - counter):
        stars.append(0)
    return stars



def book(request, book_id):
    bookx = get_object_or_404(Book, pk=book_id)
    context = dict(create_default_context())
    context['book'] = bookx
    context['favorite'] = None
    try:
        user = User.objects.get(pk=request.session['user_id'])
        context['user'] = user
    except:
        pass

    try:
        favorite = Favorite_book.objects.get(favorite_user=user, favorite_movie=bookx)
        context['favorite'] = '+'
    except:
        pass
    return render(request, "mainapp/book.html", context)




def create_default_context():
    books = Book.objects.order_by('book_main_rating')
    countries = Country.objects.all()
    categories = Category.objects.all()
    new_books = Book.objects.order_by('book_year')[:2]
    books_category_1 = Book.objects.filter(book_categories = categories[0])
    context = {'books': books,
               'countries': countries,
               'new_books': new_books,
               'categories': categories,
               'books_category_1': books_category_1,
               'user': None,
               'error': None}
    return context


def search(request):
    user = None
    try:
        user = User.objects.get(pk=request.session['user_id'])
        print("user id barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
    except:
        pass
    try:
        searched_text = request.POST['searched_text'].lower()
        found_books = []
        books = Book.objects.all()
        for book in books:
            if book.book_name.lower().count(searched_text) > 0 or book.book_desctiption.lower().count(
                    searched_text) > 0:
                found_books.append(book)
        return render(request, "mainapp/search.html", {'found_books': found_books, 'user': user})
    except:
        pass

def exit_from_account(request):
    books = Book.objects.order_by('book_main_rating')
    genres = Genre.objects.all()
    countries = Country.objects.all()
    new_books = Book.objects.order_by('book_year')[:2]
    context = {'books': books,
               'genres': genres,
               'countries': countries,
               'new_books': new_books,
               'user': None,
               'error': None}
    try:
        if request.session['user_id']:
            del request.session['user_id']
    except:
        pass
    return HttpResponseRedirect(reverse('mainapp:index'))

BookStore/mainapp/templates/mainapp/book.html
{% extends 'mainapp/wrapper.html' %}
{% load static %}
{% block content %}
<div id="wrapper">
    <div id="movieTitle"><h2>{{ book.book_name }}</h2></div>
    <div id="movieContent">
        <div id="moviePhoto">
            {% if book.book_image %}
            <img src="{{ book.book_image.url }}" alt="Djoker" width="283px" height="390px">
            {% else %}
            <img src="{% static book.book_url_image %}" alt="Djoker" width="283px" height="390px">
            {% endif %}
        </div>
        <div id="movieDescription"><p>{{ book.book_desctiption }}</p>
            <p>
                <strong>Название: </strong>{{ book.book_name }}
                <br>
                <strong>Год выпуска: </strong>{{book.book_year}}
                <br>
                <strong>Страна: </strong>{{book.book_country}}
                <br>
                <strong>Жанр: </strong>{{book.book_categories}}
                <br>
                <strong> Цена: </strong>{{ book.book_price }}
                 <br>
                <strong> Код товара: </strong>{{ book.book_cod }}
                <br>
                <strong> <a href="https://t.me/OnayRead_bot" style="width: 200px;"></a> </strong><a> Telegram bot - OnayRead </a>
            </p>
        </div>
        <div class="block-stars">
        </div>
    		<div>
    		</div>
    </div>
    </div>
</div>
<div>

</div>
{% endblock %}

BookStore/mainapp/templates/mainapp/wrapper.html
<!DOCTYPE html>
<html>
<head>
<title>OnayRead</title>
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content=" Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
		<link rel="shortcut icon" href="/images/favicon.ico" type="image/i1.png">
<link href="{% static 'mainapp/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'mainapp/css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'mainapp/css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/zoomslider.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}" />
<link href="{% static 'mainapp/css/font-awesome.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'mainapp/js/modernizr-2.6.2.min.js' %}"></script>
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'mainapp/css/moviePage.css' %}">
</head>
<body>
<!--/main-header-->
  <!--/banner-section-->
	<div id="demo-1" class = "banner-inner">
		<div class="demo-inner-content">
		<!--/header-w3l-->
			   <div class="header-w3-agileits" id="home">
			     	<div class="inner-header-agile">
						<nav class="navbar navbar-default">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
							</button>
							<img src="{% static 'mainapp/images/logo.jpg' %}" class="logo" style="width: 250px; height: 170px; border-radius: 40%;">
							</div>
					<!-- navbar-header -->
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
									<ul class="nav navbar-nav">
									<li class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">По жанрам <b class="caret"></b></a>
										<ul class="dropdown-menu multi-column columns-3">
											<li>
											<div class="col-sm-4">
												<ul class="multi-column-dropdown">
													{% for category in categories %}
													<li><a href="{% url 'mainapp:books_by_category' category.id %}">{{ category.category_name }}</a></li>
													{% endfor %}
												</ul>
											</div>
											<div class="clearfix"></div>
											</li>
										</ul>
									</li>
									<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">По странам <b class="caret"></b></a>
								<ul class="dropdown-menu multi-column columns-3">
									<li>
										<div class="col-sm-4">
											<ul class="multi-column-dropdown">
												{% for country in countries %}
												<li><a href="{% url 'mainapp:books_by_country' country.id %}">{{ country.country_name }}</a></li>
												{% endfor %}
											</ul>
										</div>
										<div class="clearfix"></div>
									</li>
								</ul>
							</li>
							<li class="dropdown">
								</li>
						</ul>

					</div>
					<div class="clearfix"> </div>
				</nav>
					 <div class="w3ls_search">
									<div class="cd-main-header">
										<ul class="cd-header-buttons">
											<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
										</ul> <!-- cd-header-buttons -->
									</div>
									<div id="cd-search" class="cd-search">
										<form action="{% url 'mainapp:search' %}" method="post">
											{% csrf_token %}
											<input name="searched_text" type="search" placeholder="Поиск..." required>
										</form>
									</div>
					</div>
					<div class="w3ls_search">
									<div class="cd-main-header">
										<ul class="cd-header-buttons">
											<li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
										</ul> <!-- cd-header-buttons -->
									</div>
					</div>

			</div>

			   </div>

		</div>
    </div>
  <!--/banner-section-->
 <!--//main-header-->
	         <!--/banner-bottom-->
			  <div class="w3_agilits_banner_bootm">
			     <div class="w3_agilits_inner_bottom">
			            <div class="col-md-6 wthree_agile_login">
						     <ul>
									<li><i class="fa fa-phone" aria-hidden="true"></i> +7-(707)-707-70-70</li>
									{% if user %}
									<li>
										<form action="{% url 'mainapp:exit_from_account' %}" method="POST">
											{% csrf_token %}
											<input type="hidden" name="exit" value="yes">
											<input type="submit" value="Выход" id="exitsubmit" >
										</form>
									</li>
									<li>
										<a href="{% url 'mainapp:user' user.id %}" style="color: white; font-size: 20px;">{{ user.user_name }}</a>
									</li>
									{% else %}
									<li><a href="#" class="login"  data-toggle="modal" data-target="#myModal4">Логин</a></li>
									<li><a href="#" class="login reg"  data-toggle="modal" data-target="#myModal5">Регистрация</a></li>
									{% endif %}

								</ul>
						</div>

				</div>
			</div>
			<!--//banner-bottom-->
			 <!-- Modal1 -->
					<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" >

							<div class="modal-dialog">
							<!-- Modal content-->
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal">&times;</button>
										<h4>Логин</h4>
										<div class="login-form">
											<form action="{% url 'mainapp:authentication' %}" method="POST">
												{% csrf_token %}
												<input type="text" name="user_login" placeholder="Логин" required="">
												<input type="password" name="user_password" placeholder="Пароль" required="">
												<input type="hidden" name="login_performed" value="yes">
												<div class="tp">
													<input type="submit" value="Войти">
												</div>
												<div class="forgot-grid">
												       <div class="log-check">
														<label class="checkbox"><input type="checkbox" name="checkbox">Запомнить</label>
														</div>
														<div class="forgot">
															<a href="#" data-toggle="modal" data-target="#myModal2">Забыли пароль?</a>
														</div>
														<div class="clearfix"></div>
													</div>

											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
				<!-- //Modal1 -->
				  <!-- Modal1 -->
					<div class="modal fade" id="myModal5" tabindex="-1" role="dialog" >

										<div class="modal-dialog">
										<!-- Modal content-->
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal">&times;</button>
													<h4>Регистрация</h4>
													<div class="login-form">
														<form action="{%url 'mainapp:registration' %}" method="post">
															{% csrf_token %}
															<input type="text" name="name" placeholder="Имя" required="">
															<input type="text" name="surname" placeholder="Фамилия" required="">
															<input type="text" name="login" placeholder="Логин" required="">
															<input type="password" name="password" placeholder="Пароль" required="">
															<input type="password" name="conform-password" placeholder="Подтвердите пароль" required="">
															<div class="tp">
																<input type="submit" value="Зарегистрироваться">
															</div>
														</form>
													</div>
												</div>
											</div>
										</div>
						</div>

{% block content %}
{% endblock %}

<div class="contact-w3ls" id="contact">
			<div class="footer-w3lagile-inner">
				<h2>ПОДПИШИТЕСЬ НА НАС</h2>
				<div class="footer-contact">
					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Введите ваш адрес электронной почты...." required=" ">
						<input type="submit" value="Подписаться">
					</form>
				</div>

		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

<script src="{% static 'mainapp/js/jquery-1.11.1.min.js' %}"></script>
	<!-- Dropdown-Menu-JavaScript -->
			<script>
				$(document).ready(function(){
					$(".dropdown").hover(
						function() {
							$('.dropdown-menu', this).stop( true, true ).slideDown("fast");
							$(this).toggleClass('open');
						},
						function() {
							$('.dropdown-menu', this).stop( true, true ).slideUp("fast");
							$(this).toggleClass('open');
						}
					);
				});
			</script>
		<!-- //Dropdown-Menu-JavaScript -->


<script type="text/javascript" src="{% static 'mainapp/js/jquery.zoomslider.min.js' %}"></script>
		<!-- search-jQuery -->
				<script src="{% static 'mainapp/js/main.js' %}"></script>
			<script src="{% static 'mainapp/js/simplePlayer.js' %}"></script>
			<script>
				$("document").ready(function() {
					$("#video").simplePlayer();
				});
			</script>
			<script>
				$("document").ready(function() {
					$("#video1").simplePlayer();
				});
			</script>
			<script>
				$("document").ready(function() {
					$("#video2").simplePlayer();
				});
			</script>
				<script>
				$("document").ready(function() {
					$("#video3").simplePlayer();
				});
			</script>

			<!-- pop-up-box -->
		<script src="{% static 'mainapp/js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
	<!--//pop-up-box -->
	<script>
		$(document).ready(function() {
		$('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});

		});
	</script>
<script src="{% static 'mainapp/js/easy-responsive-tabs.js' %}"></script>
<script>
$(document).ready(function () {
$('#horizontalTab').easyResponsiveTabs({
type: 'default', //Types: default, vertical, accordion
width: 'auto', //auto or any width like 600px
fit: true,   // 100% fit in a container
closed: 'accordion', // Start closed if in accordion view
activate: function(event) { // Callback function if tab is switched
var $tab = $(this);
var $info = $('#tabInfo');
var $name = $('span', $info);
$name.text($tab.text());
$info.show();
}
});
$('#verticalTab').easyResponsiveTabs({
type: 'vertical',
width: 'auto',
fit: true
});
});
</script>
<link href="{% static 'mainapp/css/owl.carousel.css' %}" rel="stylesheet" type="text/css" media="all">
<script src="{% static 'mainapp/js/owl.carousel.js' %}"></script>
<script>
	$(document).ready(function() {
		$("#owl-demo").owlCarousel({

		 autoPlay: 3000, //Set AutoPlay to 3 seconds
		  autoPlay : true,
		   navigation :true,

		  items : 5,
		  itemsDesktop : [640,4],
		  itemsDesktopSmall : [414,3]

		});

	});
</script>

<!--/script-->
<script type="text/javascript" src="{% static 'mainapp/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'mainapp/js/easing.js' %}"></script>

<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
</script>
 <script type="text/javascript">
						$(document).ready(function() {
							/*
							var defaults = {
					  			containerID: 'toTop', // fading element id
								containerHoverID: 'toTopHover', // fading element hover id
								scrollSpeed: 1200,
								easingType: 'linear'
					 		};
							*/

							$().UItoTop({ easingType: 'easeOutQuart' });

						});
					</script>
<!--end-smooth-scrolling-->
	<script src="{% static 'mainapp/js/bootstrap.js' %}"></script>


</div>
</div>
</body>
</body>
</html>